name: 'tftools'
description: 'Install terraform tools'
inputs:
  tfenv-version:
    description: 'Version of tfenv to install'
    required: false
    default: '2.2.2'
  tgenv-version:
    description: 'Version of tgenv to install'
    required: false
    default: '0.1.0'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install_tftools.sh
      env:
        TFENV_VERSION: ${{ inputs.tfenv-version }}
        TGENV_VERSION: ${{ inputs.tgenv-version }}
      shell: bash