name: 'aws-terraform-tools'
description: 'Install terraform tool stack'
inputs:
  tfenv-version:
    description: 'tfenv version to install'
    required: false
    default: '2.2.2'
  tgenv-version:
    description: 'tgenv version to install'
    required: false
    default: '0.1.0'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/scripts/install_tools.sh
      env:
        TFENV_VERSION: ${{ inputs.tfenv-version }}
        TGENV_VERSION: ${{ inputs.tgenv-version }}
      shell: bash